### PR TITLE
feat(setup): Create initial setup

### LINKED ISSUE #2: Create initial setup project

### PR DESCRIPTION
**Pull request by andrelas1**
Resolve #2

### CODE REVIEW

**Comment by jouderianjr** [comment]
Should this PR define the project architecture? 🤔

**Comment by paulonotz0r** [comment]
I think this PR resolves #1 and part of #3 too.

**Comment by andrelas1** [comment]
This is a very basic setup.. linter, commit lint, koa and ES6. However, I think we should define the technologies that we will use (database?) and in another issue do a PR of the initial architecture, with a well defined folder structure and our approach to organize the project (by feature)?

**Comment by paulonotz0r** [comment]
@andrelas1 Indeed. Following this to keep things (with differents purposes) separated and better structured.

**Comment by andrelas1** [comment]
hey boysies, I will make some changes to this PR. There are some babel packages that are redundant ("babel-preset-es2015"), as nodejs can already understand ES6 and the "stage-0" plugin is something that I don't think we should use. Also, on the .babelrc file, I will make some changes to babel transpile stuff that node needs (according to this -> https://github.com/babel/babel-preset-env).
Also, I think a bundler like Webpack would be beneficial in our project, so this PR could also include additional configuration to use Webpack. 
Thoughts?

**Comment by jvcjunior** [comment]
Go ahead @andrelas1 !! We need this initial setup to create/configure other stuff!

**Pull request merged**
